apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: ca-issuer
  namespace: animal-rescue
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: rescue-cert
  namespace: animal-rescue
spec:
  secretName: rescue-cert-tls
  dnsNames:
    - animal-rescue.tap.h2o-4-512.h2o.vmware.com
  issuerRef:
    name: ca-issuer
