apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: rescue-cert
  namespace: animal-rescue
spec:
  # Secret names are always required.
  secretName: rescue-cert-tls
  duration: 2160h # 90d
  renewBefore: 360h # 15d
  organization:
    - vmware
  commonName: animal-rescue.dragonstone.tkg-aws-e2-lab.winterfell.be
  isCA: false
  keySize: 2048
  keyAlgorithm: rsa
  keyEncoding: pkcs1
  # At least one of a DNS Name, USI SAN, or IP address is required.
  dnsNames:
    - animal-rescue.dragonstone.tkg-aws-e2-lab.winterfell.be
  # 
  issuerRef:
    name: letsencrypt-contour-cluster-issuer
    # We can reference ClusterIssuers by changing the kind here.
    # The default value is Issuer (i.e. a locally namespaced Issuer)
    kind: ClusterIssuer