apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dev-space

secretGenerator:
  - name: sso-credentials
    envs:
      - backend/secrets/sso-credentials.txt
    type: Opaque

generatorOptions:
  disableNameSuffixHash: true

resources:
  - frontend/tap/animal-rescue-frontend-mapping.yaml
  - frontend/tap/animal-rescue-frontend-route-config.yaml
  - backend/tap/animal-rescue-backend-mapping.yaml
  - backend/tap/animal-rescue-backend-route-config.yaml
  - gateway/gateway-tap.yaml
  - gateway/sso-secret-for-gateway
