apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: animal-rescue-frontend
  labels:
    apps.tanzu.vmware.com/workload-type: web-dev
    app.kubernetes.io/part-of: animal-rescue-frontend
  annotations:
    autoscaling.knative.dev/minScale: '1'
spec:
  source:
    git:
      url: https://github.com/jianhuabi/animal-rescue
      ref:
        branch: main
    subPath: frontend
  params:
    - name: clusterBuilder
      value: full
