apiVersion: 'tanzu.vmware.com/v1'
kind: SpringCloudGatewayRouteConfig
metadata:
  name: animal-rescue-backend-route-config
spec:
  service:
    name: animal-rescue-backend
  routes:
    - predicates:
        - Path=/animals
        - Method=GET
      filters:
        - RateLimit=2,10s
        - StripPrefix=0
      uri: http://animal-rescue-backend.dev-space.svc.cluster.local
      tags:
        - 'pet adoption'
      title: 'Retrieve pets/animal for adoption.'
      description: 'Retrieve all of the animals who are up for pet adoption.'
    - predicates:
        - Path=/animals/{animalId}/adoption-requests
        - Method=POST
      filters:
        - StripPrefix=0
      ssoEnabled: true
      tokenRelay: true
      uri: http://animal-rescue-backend.dev-space.svc.cluster.local
      tags:
        - 'pet adoption'
      title: 'Pet adoption API'
      description: 'Create pet adoption requests.'
      model:
        responses:
          '201':
            description: 'Adoption request created successfully.'
        requestBody:
          description: Manage adoption requests
          content:
            'application/json':
              schema:
                type: object
                description: Adoption request schema
                properties:
                  adopterName:
                    type: string
                  email:
                    type: string
                    format: email
                  notes:
                    type: string
                required: ['adopterName', 'email']
    - predicates:
        - Path=/animals/{animalId}/adoption-requests/{adoptionId}
        - Method=PUT,DELETE
      uri: http://animal-rescue-backend.dev-space.svc.cluster.local
      ssoEnabled: true
      tokenRelay: true
      tags:
        - 'pet adoption'
      filters:
        - Scopes=animals.adopt
        - StripPrefix=0
      title: 'Pet adoption API'
      description: 'Update/delete pet adoption requests.'
      model:
        requestBody:
          description: Manage adoption requests
          content:
            'application/json':
              schema:
                type: object
                description: Adoption request schema
                properties:
                  adopterName:
                    type: string
                  email:
                    type: string
                    format: email
                  notes:
                    type: string
                required: ['adopterName', 'email']
    - predicates:
        - Path=/actuator/**
      uri: http://animal-rescue-backend.dev-space.svc.cluster.local
      filters:
        - StripPrefix=0
      tags:
        - actuator
      title: 'API Actuator endpoints'
      description: 'Access API actuator endpoints to provide current status of backend service.'
    - predicates:
        - Path=/whoami
        - Method=GET
      filters:
        - StripPrefix=0
      uri: http://animal-rescue-backend.dev-space.svc.cluster.local
      ssoEnabled: true
      tokenRelay: true
      tags:
        - sso
      title: 'Retrieve user information'
      description: "Retrieve the current authenticated user's information."
